---
title: "Assignment 5"
author: "Nathan and Sydney"
format: html
editor: visual
---

# Metal Recycling Program

Workflow:

1.  Metal Production (S)

2.  Collection (S)

3.  Recycling (N)

4.  Waste (N)

5.  Cost of Electricity (S)

6.  Metal Switching (N)

## Setup

```{r}
# clear the environment
rm(list = ls())
sd

```

```{r}
# load needed libraries
library(here)
```

# Main Program

## Create Vectors

```{r}

# make a dataframe with metal ore information
## steel, aluminum, copper
## we don't need to keep this, I just used it for testing

metal= c("steel","aluminum","copper")

metal_ore<- data.frame(
  metal=metal,
  mass = runif(length(metal), 1,100),
  production_rate = runif(length(metal), 0,1),
  recycling_rate = runif(length(metal), 0,1),
  electricity_cost = runif(length(metal), 0,100)
)
```

## Initialize Values

```{r}

# initialize recyling value
recycled_metal<- 0

```

## Modules

### Module 1: Metal Production 

```{r}

# call the metal production module
source(here("modules/metal_production.R"))

## run it
produced_metal<- metal_production(metal_ore$mass[1], 
                                 recycled_metal, 
                                 metal_ore$production_rate[1])
produced_metal

```

### Module 2: Collection 

```{r}
# collection
source(here())
```

### Module 3: Recycling 

```{r}
# recycling
source(here())
```

### Module 4: Waste 

```{r}
# waste
source(here())

```

### Module 5: Cost of Electricity 

```{r}
# cost of electricity
source(here())

```

### Module 6: Metal Switching Module

```{r}
# metal switching
source(here())

```
